name:    basen
version: 0.1.0.0
github:  "LibreCybernetics/basen-hs"
license: OtherLicense
author:  LibreCybernetics

extra-source-files:
- README.md

description: Please see the README

dependencies:
- name: base
  version: ">= 4.12.0.0 && < 4.14"
- name: bytestring
  version: ">= 0.10.8.2 && < 0.11"
- name: text
  version: ">= 1.2.3.1 && < 1.3"

ghc-options:
- -Wall

extensions: OverloadedIntegers OverloadedStrings

library:
  source-dirs: src

executables:
  basen-app:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basen

tests:
  basen-test:
    main:        TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basen
    - quickcheck-instances
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-quickcheck
